name: startup_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.8.0
  flutter_riverpod: ^2.6.0
  go_router: ^14.0.0
  google_fonts: ^6.2.0
  font_awesome_flutter: ^10.7.0
  equatable: ^2.0.5
  get_it: ^7.7.0
  http: ^1.2.0
  file_picker: ^10.3.8
  flutter_dotenv: ^5.2.1
  googleapis_auth: ^2.0.0
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/.env

